# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea12bafa9245fdbba7b5b3df57425d2a102cae62b61dda5ed8bd97ba06430b7c6c5466d50cf4fcc7412e9385a8fbea2250170ebfabcbfc52e91f7c5364763131

test:
  secret_key_base: 6080a334fbc694c2fa19008f1724f8ef91d44e88ac0ab0f54e1cb8f130e1e6bfc441ae8c89e4d12dbb09f45add50b83486c9998dcbe1f25e17d240323a3a4d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
